version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    networks:
      - quote-net
    environment:
      MONGO_INITDB_DATABASE: quote_db

  quote-app:
    build: .
    container_name: quote-app
    networks:
      - quote-net
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017

networks:
  quote-net:
    driver: bridge
