apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetris
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GokulGk01/Tetris-k8s-manifests.git
    targetRevision: master
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: tetris
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true