apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-collector
  namespace: quote-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-collector
  template:
    metadata:
      labels:
        app: quote-collector
    spec:
      serviceAccountName: quote-collector-sa
      containers:
        - name: app
          image: ghcr.io/jolillie/quote-collector:blue
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_URI