apiVersion: v1
kind: Service
metadata:
  name: quote-collector-service
spec:
  selector:
    app: quote-collector
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer