---
- name: Setup MongoDB Backup Script and Cron
  hosts: aws_db_server
  become: true
  tasks:

    - name: Ensure backup and log directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /usr/local/bin
        - /var/log

    - name: Copy MongoDB backup script
      ansible.builtin.copy:
        src: scripts/mongo_backup.sh
        dest: /usr/local/bin/mongo_backup.sh
        owner: root
        group: root
        mode: '0755'

    - name: Ensure AWS CLI is installed
      ansible.builtin.package:
        name: awscli
        state: present

    - name: Add cron job to run backup every 6 hours
      ansible.builtin.cron:
        name: "MongoDB Backup to S3"
        user: root
        job: "/usr/local/bin/mongo_backup.sh"
        minute: "0"
        hour: "*/6"
