name: Deploy ArgoCD to EKS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name demo_cluster

    - name: Create ArgoCD Namespace
      run: |
        kubectl create namespace argocd || true
        kubectl label namespace argocd eks.amazonaws.com/fargate-profile=default --overwrite

    - name: Deploy ArgoCD
      run: |
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    - name: Expose ArgoCD Server via LoadBalancer
      run: |
        kubectl patch svc argocd-server -n argocd \
          -p '{"spec": {"type": "LoadBalancer"}}'